=== universal-verify/trust-list/trust-list.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Trust List",
  "type": "array",
  "description": "A list of trusted issuers for digital identity verification",
  "items": {
    "type": "object",
    "required": ["issuer_id", "entity_type", "name"],
    "properties": {
      "issuer_id": {
        "type": "string",
        "description": "DID or unique identifier for the issuer"
      },
      "entity_type": {
        "type": "string",
        "enum": [
          "government",
          "educational_institution",
          "commercial",
          "non_profit",
          "international_body",
          "federated_network",
          "other"
        ],
        "description": "The high-level category of the entity acting as the issuer"
      },
      "name": {
        "type": "string",
        "description": "Official name for the entity"
      },
      "certificates": {
        "type": "array",
        "items": {
          "type": "object",
          "required": ["certificate", "certificate_format", "source"],
          "properties": {
            "certificate": {
              "type": "string",
              "description": "PEM-encoded X.509 certificate used for document signing"
            },
            "certificate_format": {
              "type": "string",
              "enum": ["pem"],
              "description": "Format of the certificate (currently only PEM is supported)"
            },
            "source": {
              "type": "string",
              "description": "Source of the entity information",
              "minLength": 1
            },
            "allowExpired": {
              "type": "boolean",
              "description": "Whether to allow expired certificates"
            }
          },
          "additionalProperties": false
        },
        "minItems": 1,
        "description": "Array of certificates issued with the same subject key identifier with the most recent first. It is expected that only one certificate per subject is present, so if only updating the expiration date, the old certificate should be removed when adding the new one."
      }
    },
    "additionalProperties": false,
    "allOf": [
      {
        "if": {
          "properties": {
            "issuer_id": {
              "type": "string",
              "pattern": "^x509_aki:"
            }
          }
        },
        "then": {
          "required": ["certificates"]
        }
      }
    ]
  }
}

=== universal-verify/trust-list/trust-list.json
[
  {
    "issuer_id": "x509_aki:o6sbAJOdtI7_VxKIDCy1e7kIXaM",
    "entity_type": "government",
    "name": "Arizona Department of Transportation",
    "certificates": [
      {
        "certificate": "-----BEGIN CERTIFICATE-----\nMIIDAjCCAqigAwIBAgIUJeEs8QFyKHKe14//RgjijMhd77kwCgYIKoZIzj0EAwIw\nfzESMBAGA1UEAwwJTVZNUHJvZENBMS0wKwYDVQQKDCRBcml6b25hIERlcGFydG1l\nbnQgb2YgVHJhbnNwb3J0YXRpb24xCzAJBgNVBAsMAklUMQswCQYDVQQGEwJVUzEO\nMAwGA1UECAwFVVMtQVoxEDAOBgNVBAcMB1Bob2VuaXgwHhcNMjMwODIxMTk1NTE0\nWhcNMzExMDA1MTk1NTE0WjB/MRIwEAYDVQQDDAlNVk1Qcm9kQ0ExLTArBgNVBAoM\nJEFyaXpvbmEgRGVwYXJ0bWVudCBvZiBUcmFuc3BvcnRhdGlvbjELMAkGA1UECwwC\nSVQxCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVVUy1BWjEQMA4GA1UEBwwHUGhvZW5p\neDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLrONskCsr38QbSzauflaxfVcUJN\nigQ5XLLZ1CMlQ2xbwrYS3XfnHko6hkLU71oQa06XYYsZTSwbq9yuIfgwRYmjggEA\nMIH9MGwGA1UdHwRlMGMwYaBfoF2GW2h0dHBzOi8vbXZtcHVibGljLmJsb2IuY29y\nZS51c2dvdmNsb3VkYXBpLm5ldC9jZXJ0aWZpY2F0ZS1yZXZvY2F0aW9uLWxpc3Qv\nTVZNUHJvZENBLmNybC5wZW0wLAYDVR0SBCUwI4YhaHR0cHM6Ly9hemRvdC5nb3Yv\nbXZkL2NvbnRhY3QtbXZkMB0GA1UdDgQWBBSjqxsAk520jv9XEogMLLV7uQhdozAf\nBgNVHSMEGDAWgBSjqxsAk520jv9XEogMLLV7uQhdozAPBgNVHRMBAf8EBTADAQH/\nMA4GA1UdDwEB/wQEAwIBBjAKBggqhkjOPQQDAgNIADBFAiEAonxClPWmIGSA3NaB\nylytzq1MZHcB0vcPZIn1DVyH+hACIB6W2VnK3JVJ/nlpi8y1cFLxa8DJQ/GPWB7i\n5Mz0G3n5\n-----END CERTIFICATE-----",
        "certificate_format": "pem",
        "source": "https://azmvdnow.gov/certificates/"
      }
    ]
  }, {
    "issuer_id": "x509_aki:u311Z5J6b8-fcnu4Cvc3L5wMUDY",
    "entity_type": "government",
    "name": "California Department of Motor Vehicles",
    "certificates": [
      {
        "certificate": "-----BEGIN CERTIFICATE-----\nMIICPzCCAeWgAwIBAgIUXd0okOOM5cylFwc2WNK7D2O+ArAwCgYIKoZIzj0EAwIw\nUTELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVTLUNBMQ8wDQYDVQQKDAZDQS1ETVYx\nITAfBgNVBAMMGENhbGlmb3JuaWEgRE1WIElBQ0EgUm9vdDAeFw0yMzAzMDExNzE3\nMzlaFw0zMzAxMDcxNzE3MzlaMFExCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVVUy1D\nQTEPMA0GA1UECgwGQ0EtRE1WMSEwHwYDVQQDDBhDYWxpZm9ybmlhIERNViBJQUNB\nIFJvb3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARgzKB5QsRXYGxmIapA3ilL\noXCDxgTMI2JArA72VQ9gL2DIKkBAclKYtix7vQwUbhbH76mnmbOFSxYlCJtilfl1\no4GaMIGXMB0GA1UdDgQWBBS7fXVnknpvz59ye7gK9zcvnAxQNjASBgNVHRMBAf8E\nCDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAfBgNVHRIEGDAWgRRpYWNhLXJvb3RA\nZG12LmNhLmdvdjAxBgNVHR8EKjAoMCagJKAihiBodHRwczovL2NybC5kbXYuY2Eu\nZ292L2lhY2Evcm9vdDAKBggqhkjOPQQDAgNIADBFAiAJriK4wEUzgDCK++tIIW+g\nXASUIIcG/XhBNxuk2uHd7QIhAKWC8LFaM8qFsvlujtZZf647zD8BBc6kicj1Imw/\nwujS\n-----END CERTIFICATE-----",
        "certificate_format": "pem",
        "source": "https://www.dmv.ca.gov/portal/ca-dmv-wallet/mdl-reader/"
      }
    ]
  }, {
    "issuer_id": "x509_aki:6TUKCCDc7eWtyioiOjoDMSChidw",
    "entity_type": "government",
    "name": "Colorado Department of Revenue",
    "certificates": [
      {
        "certificate": "-----BEGIN CERTIFICATE-----\nMIIC5zCCAoygAwIBAgITF20opr5lffOr5qTJw5JHVOM0QDAKBggqhkjOPQQDAjCB\njzEOMAwGA1UECBMFVVMtQ08xCzAJBgNVBAYTAlVTMQ8wDQYDVQQHEwZEZW52ZXIx\nJzAlBgNVBAoTHkNvbG9yYWRvIERlcGFydG1lbnQgb2YgUmV2ZW51ZTESMBAGA1UE\nCxMJQ08gRFJJVkVTMSIwIAYDVQQDExlDb2xvcmFkbyBSb290IENlcnRpZmljYXRl\nMB4XDTIzMDgyOTA2MDAwMFoXDTI4MDgyODA2MDAwMFowgY8xDjAMBgNVBAgTBVVT\nLUNPMQswCQYDVQQGEwJVUzEPMA0GA1UEBxMGRGVudmVyMScwJQYDVQQKEx5Db2xv\ncmFkbyBEZXBhcnRtZW50IG9mIFJldmVudWUxEjAQBgNVBAsTCUNPIERSSVZFUzEi\nMCAGA1UEAxMZQ29sb3JhZG8gUm9vdCBDZXJ0aWZpY2F0ZTBZMBMGByqGSM49AgEG\nCCqGSM49AwEHA0IABMO19kGKFG1PhA7pv0fRjrGydwWryixCNpJyF5X7j/XLIhNH\nIMM7vN3B4jfCSiflNbnzPU1gdSsDvoIx6Fab3IyjgcQwgcEwDgYDVR0PAQH/BAQD\nAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOk1Cggg3O3lrcoqIjo6AzEg\noYncMCQGA1UdEgQdMBuGGWh0dHBzOi8vZG12LmNvbG9yYWRvLmdvdi8wRwYDVR0f\nBEAwPjA8oDqgOIY2aHR0cHM6Ly9kZXYubW9iaWxlZGwuY29tLzUwcHdzL0NSTC9t\nREwvcmV2b2NhdGlvbnMuY3JsMBAGCSsGAQQBg8UhAQQDNTBQMAoGCCqGSM49BAMC\nA0kAMEYCIQCwMT0ZUKZpY4S/dF/Vq+5Zpa+3DOp1IU0kr8i0OiMaQwIhAOmmpLD3\ncM4VR9j3SHiSXn8t3814J6XocI5zvP5pTe5e\n-----END CERTIFICATE-----",
        "certificate_format": "pem",
        "source": "http://dmv.colorado.gov/applewallet/"
      }
    ]
  }, {
    "issuer_id": "x509_aki:r80lNkIAOQqsAzYOPCWKL5QE-TU",
    "entity_type": "government",
    "name": "Georgia Department of Driver Services",
    "certificates": [
      {
        "certificate": "-----BEGIN CERTIFICATE-----\nMIIDRzCCAu2gAwIBAgITVgO3G2afw4UBNWRnxbpYWrG5uTAKBggqhkjOPQQDAjCB\nnTEOMAwGA1UECBMFVVMtR0ExCzAJBgNVBAYTAlVTMRAwDgYDVQQHEwdDb255ZXJz\nMS4wLAYDVQQKEyVHZW9yZ2lhIERlcGFydG1lbnQgb2YgRHJpdmVyIFNlcnZpY2Vz\nMQ8wDQYDVQQLEwZEUklWRVMxKzApBgNVBAMTIkdlb3JnaWEgUm9vdCBDZXJ0aWZp\nY2F0ZSBBdXRob3JpdHkwHhcNMjQwMzIwMDQwMDAwWhcNMjkwMzIwMDQwMDAwWjCB\nnTEOMAwGA1UECBMFVVMtR0ExCzAJBgNVBAYTAlVTMRAwDgYDVQQHEwdDb255ZXJz\nMS4wLAYDVQQKEyVHZW9yZ2lhIERlcGFydG1lbnQgb2YgRHJpdmVyIFNlcnZpY2Vz\nMQ8wDQYDVQQLEwZEUklWRVMxKzApBgNVBAMTIkdlb3JnaWEgUm9vdCBDZXJ0aWZp\nY2F0ZSBBdXRob3JpdHkwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASsRp10nCFK\ntW6sJL0xMPMKDCkeKFccLdRGKl2gN9tnzGi9aEee3z9S+vOH2EKTxFVmiqEmCS1u\n5LXCKkLIq+D+o4IBCDCCAQQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYB\nAf8CAQAwHQYDVR0OBBYEFK/NJTZCADkKrAM2Djwlii+UBPk1MEgGA1UdEgRBMD+B\nI2dyb3VwaXRwcm9kdWN0aW9uc3VwcG9ydEBkZHMuZ2EuZ292hhhodHRwczovL2Rk\ncy5nZW9yZ2lhLmdvdi8wYwYDVR0fBFwwWjBYoFagVIZSaHR0cHM6Ly93cy5kcml2\nZXMuZ2EuZ292L1dlYlNlcnZpY2VzL05BL0dTUC9jZXJ0aWZpY2F0ZS9yZXZvY2F0\naW9uL3Jldm9jYXRpb25zLmNybDAQBgkrBgEEAYPFIQEEA0dTUDAKBggqhkjOPQQD\nAgNIADBFAiBsNDY02UQq8xatSFHgcdQY64lL0EaaYKsDQ3AvZGjPgAIhAJtOn2wk\num9vlccuEFL8XIgL6XHl2jEQSNKadqLoOk+T\n-----END CERTIFICATE-----",
        "certificate_format": "pem",
        "source": "https://dds.georgia.gov/georgia-licenseid/ga-digital-drivers-license"
      }
    ]
  }, {
    "issuer_id": "x509_aki:wIMUjJhBaVaYzZW1YzMQ0NqBe80",
    "entity_type": "government",
    "name": "Hawaii Department of Transportation",
    "certificates": [
      {
        "certificate": "-----BEGIN CERTIFICATE-----\nMIIC3DCCAoKgAwIBAgIQO0MRI6jbr3YzWm0a/hWz7zAKBggqhkjOPQQDAjCBiDEL\nMAkGA1UEBhMCVVMxJTAjBgNVBAoMHERlcGFydG1lbnQgb2YgVHJhbnNwb3J0YXRp\nb24xGDAWBgNVBAsMD1N0YXRlIG9mIEhhd2FpaTEOMAwGA1UECAwFVVMtSEkxFTAT\nBgNVBAMMDEhJX0lBQ0FfUHJvZDERMA8GA1UEBwwISG9ub2x1bHUwHhcNMjQwNjA1\nMjEzNzI0WhcNMzQwNjAzMjIzNzI0WjCBiDELMAkGA1UEBhMCVVMxJTAjBgNVBAoM\nHERlcGFydG1lbnQgb2YgVHJhbnNwb3J0YXRpb24xGDAWBgNVBAsMD1N0YXRlIG9m\nIEhhd2FpaTEOMAwGA1UECAwFVVMtSEkxFTATBgNVBAMMDEhJX0lBQ0FfUHJvZDER\nMA8GA1UEBwwISG9ub2x1bHUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARCcrrc\n8mVy8VHxjpV8ZfO8alQwpFRCT8kazy5f/iPEQPSsqc0pj6LdbLQdqXEaokUDKwcx\nfpdN0uaDk5MGWTFZo4HLMIHIMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYE\nFMCDFIyYQWlWmM2VtWMzENDagXvNMA4GA1UdDwEB/wQEAwIBBjAfBgNVHRIEGDAW\nhhRodHRwczovL21kbC5obmwuaW5mbzBiBgNVHR8EWzBZMFegVaBThlFodHRwOi8v\nZDE3NWdjZzB6YzI4dGkuY2xvdWRmcm9udC5uZXQvY3JsLzlkNTE3MmZmLWZhMDYt\nNDJiMy04Zjc0LTI2OTM4ZjdkYWI0Yy5jcmwwCgYIKoZIzj0EAwIDSAAwRQIhAOrQ\ne8YV+0FSVI8EoNZeQklQvzql0UfTs2/+VxB4DnJdAiAuhccsfdM5gsysRhtdTuSL\n+G1QKJa/XMMZxJFWh/ozjg==\n-----END CERTIFICATE-----",
        "certificate_format": "pem",
        "source": "https://hidot.hawaii.gov/highways/mobile-driver-license/"
      }
    ]
  }, {
    "issuer_id": "x509_aki:TprRzaFBJ1SLjJsO01tlLCQ4YF0",
    "entity_type": "government",
    "name": "Maryland MVA",
    "certificates": [
      {
        "certificate": "-----BEGIN CERTIFICATE-----\nMIICxjCCAmygAwIBAgITJkV7El8K11IXqY7mz96n/EhiITAKBggqhkjOPQQDAjBq\nMQ4wDAYDVQQIEwVVUy1NRDELMAkGA1UEBhMCVVMxFDASBgNVBAcTC0dsZW4gQnVy\nbmllMRUwEwYDVQQKEwxNYXJ5bGFuZCBNVkExHjAcBgNVBAMTFUZhc3QgRW50ZXJw\ncmlzZXMgUm9vdDAeFw0yNDAxMDUwNTAwMDBaFw0yOTAxMDQwNTAwMDBaMGoxDjAM\nBgNVBAgTBVVTLU1EMQswCQYDVQQGEwJVUzEUMBIGA1UEBxMLR2xlbiBCdXJuaWUx\nFTATBgNVBAoTDE1hcnlsYW5kIE1WQTEeMBwGA1UEAxMVRmFzdCBFbnRlcnByaXNl\ncyBSb290MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEaWcKIqlAWboV93RAa5ad\n0LJBn8W0/yYwtOyUlxuTxoo4SPkorKmOz3EhThC+U4WRrt13aSnCsJtK+waBFghX\nu6OB8DCB7TAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNV\nHQ4EFgQUTprRzaFBJ1SLjJsO01tlLCQ4YF0wPAYDVR0SBDUwM4EWbXZhY3NAbWRv\ndC5zdGF0ZS5tZC51c4YZaHR0cHM6Ly9tdmEubWFyeWxhbmQuZ292LzBYBgNVHR8E\nUTBPME2gS6BJhkdodHRwczovL215bXZhLm1hcnlsYW5kLmdvdjo1NDQzL01EUC9X\nZWJTZXJ2aWNlcy9DUkwvbURML3Jldm9jYXRpb25zLmNybDAQBgkrBgEEAYPFIQEE\nA01EUDAKBggqhkjOPQQDAgNIADBFAiEAnX3+E4E5dQ+5G1rmStJTW79ZAiDTabyL\n8lJuYL/nDxMCIHHkAyIJcQlQmKDUVkBr3heUd5N9Y8GWdbWnbHuwe7Om\n-----END CERTIFICATE-----",
        "certificate_format": "pem",
        "source": "https://mva.maryland.gov/Pages/MDMobileID_Apple.aspx"
      }
    ]
  }, {
    "issuer_id": "x509_aki:yYcBvfzjEXhrywase5x1u3ploe4",
    "entity_type": "government",
    "name": "New Mexico Taxation and Revenue Department",
    "certificates": [
      {
        "certificate": "-----BEGIN CERTIFICATE-----\nMIIDazCCAxCgAwIBAgIUAL6HcNnhfBgU3axITbtnZchElWkwCgYIKoZIzj0EAwIw\ngcExDjAMBgNVBAgTBVVTLU5NMQswCQYDVQQGEwJVUzERMA8GA1UEBxMIU2FudGEg\nRmUxMzAxBgNVBAoTKk5ldyBNZXhpY28gVGF4YXRpb24gYW5kIFJldmVudWUgRGVw\nYXJ0bWVudDEqMCgGA1UECxMhTmV3IE1leGljbyBNb3RvciBWZWhpY2xlIERpdmlz\naW9uMS4wLAYDVQQDEyVOZXcgTWV4aWNvIFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9y\naXR5MB4XDTI0MDcyNjA2MDAwMFoXDTI5MDcyNjA2MDAwMFowgcExDjAMBgNVBAgT\nBVVTLU5NMQswCQYDVQQGEwJVUzERMA8GA1UEBxMIU2FudGEgRmUxMzAxBgNVBAoT\nKk5ldyBNZXhpY28gVGF4YXRpb24gYW5kIFJldmVudWUgRGVwYXJ0bWVudDEqMCgG\nA1UECxMhTmV3IE1leGljbyBNb3RvciBWZWhpY2xlIERpdmlzaW9uMS4wLAYDVQQD\nEyVOZXcgTWV4aWNvIFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MFkwEwYHKoZI\nzj0CAQYIKoZIzj0DAQcDQgAE4XmFaUvOxY1VPg9tUXmlMnkmR1XDLV0DFISZuO7r\nc0ibUtlTqQtm383ylWY7yDBJRZFbdRInUWwPXR1WPpFKs6OB4zCB4DAOBgNVHQ8B\nAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUyYcBvfzjEXhrywas\ne5x1u3ploe4wKQYDVR0SBCIwIIYeaHR0cHM6Ly93d3cubXZkLm5ld21leGljby5n\nb3YvMGEGA1UdHwRaMFgwVqBUoFKGUGh0dHBzOi8vc2VydmljZXMubXZkLm5ld21l\neGljby5nb3Yvc2VydmljZXMvZXh0ZXJuYWwvY3JsL2dldExpc3QvcmV2b2NhdGlv\nbnMuY3JsMBAGCSsGAQQBg8UhAQQDTlNQMAoGCCqGSM49BAMCA0kAMEYCIQCZ8a0r\nHAhopm7QruSPkrKIh8/bwyVOOtD6ogvFIXMh+AIhAIVj3b+tGjG2zIPrj7Z5doxl\nbbFqmO73V8wIs1rlFxkS\n-----END CERTIFICATE-----",
        "certificate_format": "pem",
        "source": "https://www.mvd.newmexico.gov/new-mexico-mobile-id-in-apple-wallet/"
      }
    ]
  }, {
    "issuer_id": "x509_aki:Lx4k_1KTsUo51qvuBREJwYHbXwg",
